export interface ILeague {
  id: string;
  name: string;
  country: string;
  continent: string;
}

export const league = [
  {
    id: "WC",
    name: "FIFA World Cup",
    country: "International",
    continent: "International",
  },
  {
    id: "EURO_CUP",
    name: "UEFA European Championship",
    country: "Europe",
    continent: "Europe",
  },
  {
    id: "UEFA_CL",
    name: "UEFA Champions League ",
    country: "Europe",
    continent: "Europe",
  },
  {
    id: "UEFA_EL",
    name: "UEFA Europa League",
    country: "Europe",
    continent: "Europe",
  },
  {
    id: "UEFA_ECL",
    name: "UEFA Conference League",
    country: "Europe",
    continent: "Europe",
  },
  {
    id: "UEFA_NL",
    name: "UEFA Nations League",
    country: "England",
    continent: "Europe",
  },
  {
    id: "ENG_PR",
    name: "English Premier League",
    country: "England",
    continent: "Europe",
  },
  {
    id: "ITA_D1",
    name: "Italian Serie A ",
    country: "Italy",
    continent: "Europe",
  },
  {
    id: "SPA_D1",
    name: "Spanish La Liga ",
    country: "Spain",
    continent: "Europe",
  },
  {
    id: "GER_D1",
    name: "German Bundesliga",
    country: "Germany",
    continent: "Europe",
  },
  {
    id: "FRA_D1",
    name: "France Ligue 1 ",
    country: "France",
    continent: "Europe",
  },
  {
    id: "ENG_LCH",
    name: "England Championship",
    country: "England",
    continent: "Europe",
  },
  {
    id: "ENG_L1",
    name: "England League 1",
    country: "England",
    continent: "Europe",
  },
  {
    id: "ENG_L2",
    name: "England League 2",
    country: "England",
    continent: "Europe",
  },
  {
    id: "ENG_CONF",
    name: "England Conference",
    country: "England",
    continent: "Europe",
  },
  {
    id: "ENG_FAC",
    name: "England FA Cup",
    country: "England",
    continent: "Europe",
  },
  {
    id: "ENG_LC",
    name: "England League Cup",
    country: "England",
    continent: "Europe",
  },
  {
    id: "ENG_JPT",
    name: "England Johnstone",
    country: "England",
    continent: "Europe",
  },
  {
    id: "ENG_FACS",
    name: "FA Community Shield",
    country: "England",
    continent: "Europe",
  },
  {
    id: "ITA_D2",
    name: "Italian Serie B ",
    country: "Italy",
    continent: "Europe",
  },
  {
    id: "ITA_C1",
    name: "Italy C1",
    country: "Italy",
    continent: "Europe",
  },
  {
    id: "ITA_Cup",
    name: "Coppa Italia",
    country: "Italy",
    continent: "Europe",
  },
  {
    id: "SPA_D2",
    name: "Spanish La Liga 2 ",
    country: "Spain",
    continent: "Europe",
  },
  {
    id: "SPA_D3",
    name: "Spain Primera Division RFEF",
    country: "Spain",
    continent: "Europe",
  },
  {
    id: "SPA_CUP",
    name: "Spanish Copa Del Rey",
    country: "Spain",
    continent: "Europe",
  },
  {
    id: "SPA_SUC",
    name: "Spain Supercopa de Espana",
    country: "Spain",
    continent: "Europe",
  },
  {
    id: "GER_D2",
    name: "German Bundesliga 2",
    country: "Germany",
    continent: "Europe",
  },
  {
    id: "GER_D3",
    name: "German 3.Liga",
    country: "Germany",
    continent: "Europe",
  },
  {
    id: "GERC",
    name: "Germany Cup",
    country: "Germany",
    continent: "Europe",
  },
  {
    id: "GER_SC",
    name: "German Super Cup",
    country: "Germany",
    continent: "Europe",
  },
  {
    id: "FRA_D2",
    name: "France Ligue 2",
    country: "France",
    continent: "Europe",
  },
  {
    id: "FRA_D3",
    name: "France Ligue 3",
    country: "France",
    continent: "Europe",
  },
  {
    id: "FRAC",
    name: "French Cup",
    country: "France",
    continent: "Europe",
  },
  {
    id: "FRA_LC",
    name: "French League Cup",
    country: "France",
    continent: "Europe",
  },
  {
    id: "POR_D1",
    name: "Liga Portugal 1",
    country: "Portugal",
    continent: "Europe",
  },
  {
    id: "POR_D2",
    name: "Liga Portugal 2",
    country: "Portugal",
    continent: "Europe",
  },
  {
    id: "POR_CN",
    name: "Portugal Campeonato Nacional",
    country: "Portugal",
    continent: "Europe",
  },
  {
    id: "PORLC",
    name: "Portugal League Cup",
    country: "Portugal",
    continent: "Europe",
  },
  {
    id: "POR_SC",
    name: "Portugal Super Cup",
    country: "Portugal",
    continent: "Europe",
  },
  {
    id: "SCO_PR",
    name: "Scottish Premier League",
    country: "Scotland",
    continent: "Europe",
  },
  {
    id: "SCO_CH",
    name: "Scottish Championship",
    country: "Scotland",
    continent: "Europe",
  },
  {
    id: "SCOFAC",
    name: "Scotland FA Cup",
    country: "Scotland",
    continent: "Europe",
  },
  {
    id: "SCO_LC",
    name: "Scotland League Cup",
    country: "Scotland",
    continent: "Europe",
  },
  {
    id: "HOL_D1",
    name: "Holland Eredivisie",
    country: "Netherland",
    continent: "Europe",
  },
  {
    id: "HOL_D2",
    name: "Holland Eerste Divisie",
    country: "Netherland",
    continent: "Europe",
  },
  {
    id: "HOLC",
    name: "KNVB Cup",
    country: "Netherland",
    continent: "Europe",
  },
  {
    id: "BEL_D1",
    name: "Belgian Pro League",
    country: "Belgium",
    continent: "Europe",
  },
  {
    id: "BEL_D2",
    name: "Belgian Second Division",
    country: "Belgium",
    continent: "Europe",
  },
  {
    id: "BEL_CUP",
    name: "Belgian Cup",
    country: "Belgium",
    continent: "Europe",
  },
  {
    id: "BEL_SC",
    name: "Belgium Super Cup",
    country: "Belgium",
    continent: "Europe",
  },
  {
    id: "SWE_D1",
    name: "Swedish Allsvenskan",
    country: "Sweden",
    continent: "Europe",
  },
  {
    id: "SWE_D2",
    name: "Sweden Superettan",
    country: "Sweden",
    continent: "Europe",
  },
  {
    id: "SWE_CUP",
    name: "Sweden Cupen",
    country: "Sweden",
    continent: "Europe",
  },
  {
    id: "FIN_D1",
    name: "Finland Veikkausliga",
    country: "Finland",
    continent: "Europe",
  },
  {
    id: "FIN_D2",
    name: "Finland Ykkonen",
    country: "Finland",
    continent: "Europe",
  },
  {
    id: "NOR_D1",
    name: "Norwegian Tippeligaen",
    country: "Norway",
    continent: "Europe",
  },
  {
    id: "NOR_AL",
    name: "Norway Adeccoligaen",
    country: "Norway",
    continent: "Europe",
  },
  {
    id: "NORC",
    name: "Norway NM Cupen",
    country: "Norway",
    continent: "Europe",
  },
  {
    id: "DEN_SASL",
    name: "Denmark Superligaen",
    country: "Denmark",
    continent: "Europe",
  },
  {
    id: "DEN_D1",
    name: "Danish 1st Division",
    country: "Denmark",
    continent: "Europe",
  },
  {
    id: "DEN_CUP",
    name: "Denmark Cup",
    country: "Denmark",
    continent: "Europe",
  },
  {
    id: "AUT_D1",
    name: "Austrian Bundesliga",
    country: "Austria",
    continent: "Europe",
  },
  {
    id: "SUI_SL",
    name: "Switzerland Super League",
    country: "Switzerland",
    continent: "Europe",
  },
  {
    id: "SUI_CL",
    name: "Switzerland Challenge League",
    country: "Switzerland",
    continent: "Europe",
  },
  {
    id: "SUI_CUP",
    name: "Switzerland Cup",
    country: "Switzerland",
    continent: "Europe",
  },
  {
    id: "IRE_PR",
    name: "Ireland Premier Division",
    country: "Ireland",
    continent: "Europe",
  },
  {
    id: "IRE_D1",
    name: "Ireland First Division",
    country: "Ireland",
    continent: "Europe",
  },
  {
    id: "Northern Ireland",
    name: "Northern Ireland Premier League",
    country: "Northern Ireland",
    continent: "Europe",
  },
  {
    id: "RUS_PR",
    name: "Russia Premier League",
    country: "Russia",
    continent: "Europe",
  },
  {
    id: "RUS_CUP",
    name: "Russia Cup",
    country: "Russia",
    continent: "Europe",
  },
  {
    id: "RUS_SC",
    name: "Russian Super Cup",
    country: "Russia",
    continent: "Europe",
  },
  {
    id: "POL_PR",
    name: "Poland Ekstraklasa",
    country: "Poland",
    continent: "Europe",
  },
  {
    id: "POL_D1",
    name: "Poland Liga 1",
    country: "Poland",
    continent: "Europe",
  },
  {
    id: "POL_CUP",
    name: "Poland Cup",
    country: "Poland",
    continent: "Europe",
  },
  {
    id: "POL_SC",
    name: "Poland Super Cup",
    country: "Poland",
    continent: "Europe",
  },
  {
    id: "UKR_D1",
    name: "Ukrainian Premier League",
    country: "Ukraine",
    continent: "Europe",
  },
  {
    id: "UKRC",
    name: "Ukraine Cup",
    country: "Ukraine",
    continent: "Europe",
  },
  {
    id: "CZE_D1",
    name: "Czech Republic Gambrinus Liga",
    country: "Czech Republic",
    continent: "Europe",
  },
  {
    id: "GRE_D1",
    name: "Greece Super League A",
    country: "Greece",
    continent: "Europe",
  },
  {
    id: "GRE_CUP",
    name: "Greece Cup",
    country: "Greece",
    continent: "Europe",
  },
  {
    id: "ROM_D1",
    name: "Romania Liga I",
    country: "Romania",
    continent: "Europe",
  },
  {
    id: "ROMC",
    name: "Romania Cup",
    country: "Romania",
    continent: "Europe",
  },
  {
    id: "ROM_SC",
    name: "Romania Super Cup",
    country: "Romania",
    continent: "Europe",
  },
  {
    id: "SVK D1",
    name: "Slovak Super Liga",
    country: "Slovakia",
    continent: "Europe",
  },
  {
    id: "ICE_PR",
    name: "Iceland Premier Division",
    country: "Iceland",
    continent: "Europe",
  },
  {
    id: "ICE_D1",
    name: "Iceland Division 1",
    country: "Iceland",
    continent: "Europe",
  },
  {
    id: "ICE_CUP",
    name: "Iceland Cup",
    country: "Iceland",
    continent: "Europe",
  },
  {
    id: "ICE_LC",
    name: "Iceland League Cup",
    country: "Iceland",
    continent: "Europe",
  },
  {
    id: "LAT_D1",
    name: "Latvian Higher League",
    country: "Latvia",
    continent: "Europe",
  },
  {
    id: "ISR_D1",
    name: "Israel Premier League",
    country: "Israel",
    continent: "Europe",
  },
  {
    id: "BLR_D1",
    name: "Belarusian Premier League",
    country: "Belarus",
    continent: "Europe",
  },
  {
    id: "LIT_D1",
    name: "Lithuania - 1.Division",
    country: "Lithuania",
    continent: "Europe",
  },
  {
    id: "TUR_D1",
    name: "Turkey Super Lig",
    country: "Turkey",
    continent: "Europe",
  },
  {
    id: "TFF_1._LIG",
    name: "Turkey 1. Lig",
    country: "Turkey",
    continent: "Europe",
  },
  {
    id: "TUR_CUP",
    name: "Turkey Cup",
    country: "Turkey",
    continent: "Europe",
  },
  {
    id: "TUR_SC",
    name: "Turkey Super Cup",
    country: "Turkey",
    continent: "Europe",
  },
  {
    id: "WELSH_PR",
    name: "Welsh Premier League",
    country: "Wales",
    continent: "Europe",
  },
  {
    id: "HUN_D1",
    name: "Hungary Borsodi Liga",
    country: "Hungary",
    continent: "Europe",
  },
  {
    id: "CRO_D1",
    name: "Croatia 1.Division",
    country: "Croatia",
    continent: "Europe",
  },
  {
    id: "CRO_CUP",
    name: "Croatia Cup",
    country: "Croatia",
    continent: "Europe",
  },
  {
    id: "BUL_D1",
    name: "Bulgaria Premier League",
    country: "Bulgaria",
    continent: "Europe",
  },
  {
    id: "SLO_D1",
    name: "Slovenia 1.Liga",
    country: "Slovenia",
    continent: "Europe",
  },
  {
    id: "CPY_D1",
    name: "Cyprus 1 Division",
    country: "Cyprus",
    continent: "Europe",
  },
  {
    id: "SER_D1",
    name: "Serbian Superliga",
    country: "Serbia",
    continent: "Europe",
  },
  {
    id: "KAZ_PR",
    name: "Kazakhstan Premier League",
    country: "Kazakhstan",
    continent: "Europe",
  },
  {
    id: "BOS_PL",
    name: "Bosnia and Herzegovina Premier League",
    country: "Bosnia and Herzegovina",
    continent: "Europe",
  },
  {
    id: "EST_D1",
    name: "Estonia Champions League",
    country: "Estonia",
    continent: "Europe",
  },
  {
    id: "MOL_D1",
    name: "Moldova Divizia Nationala",
    country: "Moldova",
    continent: "Europe",
  },
  {
    id: "ARM_D1",
    name: "Armenia Premier League",
    country: "Armenia",
    continent: "Europe",
  },
  {
    id: "GEO_D1",
    name: "Georgia Primera Division",
    country: "Georgia",
    continent: "Europe",
  },
  {
    id: "AZE_D1",
    name: "Azerbaijan Premier League",
    country: "Azerbaijan",
    continent: "Europe",
  },
  {
    id: "AMEC",
    name: "Copa America",
    country: "America",
    continent: "America",
  },
  {
    id: "CON_CLA",
    name: "Copa Libertadores",
    country: "America",
    continent: "America",
  },
  {
    id: "MLS",
    name: "Major League Soccer",
    country: "United States",
    continent: "America",
  },
  {
    id: "BRA_D1",
    name: "Brazil Serie A",
    country: "Brazil",
    continent: "America",
  },
  {
    id: "BRA_D2",
    name: "Brazil Serie B",
    country: "Brazil",
    continent: "America",
  },
  {
    id: "ARG_D1",
    name: "Argentine Division 1",
    country: "Argentina",
    continent: "America",
  },
  {
    id: "MEX_D1",
    name: "Primera Division Liga MX",
    country: "Mexico",
    continent: "America",
  },
  {
    id: "URU_D1",
    name: "Uruguay Primera Division",
    country: "Uruguay",
    continent: "America",
  },
  {
    id: "COL_D1",
    name: "Primera Division de Colombiano-Apertura",
    country: "Colombia",
    continent: "America",
  },
  {
    id: "BOL_D1",
    name: "Bolivia Primera Division",
    country: "Bolivia",
    continent: "America",
  },
  {
    id: "AFC",
    name: "AFC Asian Cup",
    country: "Asia",
    continent: "Asia",
  },
  {
    id: "ACLE",
    name: "AFC Champions League Elite",
    country: "Asia",
    continent: "Asia",
  },
  {
    id: "ACL2",
    name: "AFC Champions League 2",
    country: "Asia",
    continent: "Asia",
  },
  {
    id: "CHA_CSL",
    name: "Chinese Super League",
    country: "China",
    continent: "Asia",
  },
  {
    id: "JPN_D1",
    name: "J1 League",
    country: "Japan",
    continent: "Asia",
  },
  {
    id: "JPN_D2",
    name: "J2 League",
    country: "Japan",
    continent: "Asia",
  },
  {
    id: "KOR_D1",
    name: "K League 1",
    country: "South Korea",
    continent: "Asia",
  },
  {
    id: "KOR_D2",
    name: "K League 2",
    country: "South Korea",
    continent: "Asia",
  },
  {
    id: "AUS_D1",
    name: "Australia A-League",
    country: "Australia",
    continent: "Asia",
  },
  {
    id: "AUS_NSW",
    name: "NSW Premier League",
    country: "Australia",
    continent: "Asia",
  },
  {
    id: "AUS_VPL",
    name: "VIC Premier League",
    country: "Australia",
    continent: "Asia",
  },
  {
    id: "AUS_VD1",
    name: "Victorian State League Division 1",
    country: "Australia",
    continent: "Asia",
  },
  {
    id: "KSA_SPL",
    name: "Saudi Professional League",
    country: "Saudi Arabia",
    continent: "Asia",
  },
  {
    id: "KSA_D1",
    name: "Saudi Arabia Division 1",
    country: "Saudi Arabia",
    continent: "Asia",
  },
  {
    id: "IRN_PR",
    name: "Persian Gulf Pro League",
    country: "Iran",
    continent: "Asia",
  },
  {
    id: "UAE_LP",
    name: "UAE Pro-League",
    country: "UAE",
    continent: "Asia",
  },
  {
    id: "MAS_SL",
    name: "Liga Super Malaysia",
    country: "Malaysia",
    continent: "Asia",
  },
  {
    id: "BHR_D1",
    name: "Bahraini Premier League",
    country: "Bahrain",
    continent: "Asia",
  },
  {
    id: "QAT_D1",
    name: "Qatar League",
    country: "Qatar",
    continent: "Asia",
  },
  {
    id: "THA_PR",
    name: "Thai League 1",
    country: "Thailand",
    continent: "Asia",
  },
  {
    id: "THA_L2",
    name: "Thai League 2",
    country: "Thailand",
    continent: "Asia",
  },
  {
    id: "THA_LC",
    name: "Thai League Revo Cup",
    country: "Thailand",
    continent: "Asia",
  },
  {
    id: "KUW_D1",
    name: "Kuwaiti Premier League",
    country: "Kuwait",
    continent: "Asia",
  },
  {
    id: "UZB_D1",
    name: "Uzbek League",
    country: "Uzbekistan",
    continent: "Asia",
  },
  {
    id: "IND_ISL",
    name: "Indian Super League",
    country: "India",
    continent: "Asia",
  },
  {
    id: "IDN_ISL",
    name: "Indonesia Liga 1",
    country: "Indonesia",
    continent: "Asia",
  },
  {
    id: "CAF_NC",
    name: "Africa Cup of Nations",
    country: "Africa",
    continent: "Africa",
  },
  {
    id: "CAF_CL",
    name: "CAF Champions League",
    country: "Africa",
    continent: "Africa",
  },
  {
    id: "EGY_D1",
    name: "Egyptian Premier League",
    country: "Egypt",
    continent: "Africa",
  },
];
