// Array of football teams from various leagues worldwide
export const teams = [
  // England - Premier League (2022/23 season)
  { id: 1, name: "Arsenal", country: "England", code: "ARS" },
  { id: 2, name: "Manchester City", country: "England", code: "MCI" },
  { id: 3, name: "Manchester United", country: "England", code: "MUN" },
  { id: 4, name: "Newcastle United", country: "England", code: "NEW" },
  { id: 5, name: "Liverpool", country: "England", code: "LIV" },
  { id: 6, name: "Tottenham Hotspur", country: "England", code: "TOT" },
  { id: 7, name: "Chelsea", country: "England", code: "CHE" },
  { id: 8, name: "Aston Villa", country: "England", code: "AVL" },
  { id: 9, name: "Brighton", country: "England", code: "BHA" },
  { id: 10, name: "Brentford", country: "England", code: "BRE" },
  { id: 11, name: "Fulham", country: "England", code: "FUL" },
  { id: 12, name: "Crystal Palace", country: "England", code: "CRY" },
  { id: 13, name: "Wolves", country: "England", code: "WOL" },
  { id: 14, name: "West Ham", country: "England", code: "WHU" },
  { id: 15, name: "Leicester City", country: "England", code: "LEI" },
  { id: 16, name: "Leeds United", country: "England", code: "LEE" },
  { id: 17, name: "Everton", country: "England", code: "EVE" },
  { id: 18, name: "Southampton", country: "England", code: "SOU" },
  { id: 19, name: "Nottingham Forest", country: "England", code: "NOT" },
  { id: 20, name: "Bournemouth", country: "England", code: "BOU" },

  // England - Championship (2022/23)
  { id: 21, name: "Burnley", country: "England", code: "BUR" },
  { id: 22, name: "Sheffield United", country: "England", code: "SHU" },
  { id: 23, name: "Luton Town", country: "England", code: "LUT" },
  { id: 24, name: "Middlesbrough", country: "England", code: "MID" },
  { id: 25, name: "Coventry City", country: "England", code: "COV" },
  { id: 26, name: "Sunderland", country: "England", code: "SUN" },
  { id: 27, name: "West Bromwich Albion", country: "England", code: "WBA" },
  { id: 28, name: "Watford", country: "England", code: "WAT" },
  { id: 29, name: "Preston North End", country: "England", code: "PRE" },
  { id: 30, name: "Norwich City", country: "England", code: "NOR" },
  { id: 31, name: "Millwall", country: "England", code: "MIL" },
  { id: 32, name: "Swansea City", country: "England", code: "SWA" },
  { id: 33, name: "Blackburn Rovers", country: "England", code: "BLB" },
  { id: 34, name: "Bristol City", country: "England", code: "BRI" },
  { id: 35, name: "Hull City", country: "England", code: "HUL" },
  { id: 36, name: "Stoke City", country: "England", code: "STK" },
  { id: 37, name: "Birmingham City", country: "England", code: "BIR" },
  { id: 38, name: "Huddersfield Town", country: "England", code: "HUD" },
  { id: 39, name: "Rotherham United", country: "England", code: "ROT" },
  { id: 40, name: "Queens Park Rangers", country: "England", code: "QPR" },
  { id: 41, name: "Cardiff City", country: "England", code: "CAR" },
  { id: 42, name: "Reading", country: "England", code: "REA" },
  { id: 43, name: "Wigan Athletic", country: "England", code: "WIG" },
  { id: 44, name: "Blackpool", country: "England", code: "BLA" },

  // England - League One (2022/23)
  { id: 45, name: "Plymouth Argyle", country: "England", code: "PLY" },
  { id: 46, name: "Ipswich Town", country: "England", code: "IPS" },
  { id: 47, name: "Sheffield Wednesday", country: "England", code: "SHW" },
  { id: 48, name: "Barnsley", country: "England", code: "BAR" },
  { id: 49, name: "Bolton Wanderers", country: "England", code: "BOL" },
  { id: 50, name: "Peterborough United", country: "England", code: "PET" },
  { id: 51, name: "Derby County", country: "England", code: "DER" },
  { id: 52, name: "Portsmouth", country: "England", code: "POR" },
  { id: 53, name: "Wycombe Wanderers", country: "England", code: "WYC" },
  { id: 54, name: "Charlton Athletic", country: "England", code: "CHA" },
  { id: 55, name: "Lincoln City", country: "England", code: "LIN" },
  { id: 56, name: "Shrewsbury Town", country: "England", code: "SHR" },
  { id: 57, name: "Fleetwood Town", country: "England", code: "FLE" },
  { id: 58, name: "Exeter City", country: "England", code: "EXE" },
  { id: 59, name: "Burton Albion", country: "England", code: "BUR" },
  { id: 60, name: "Bristol Rovers", country: "England", code: "BRS" },
  { id: 61, name: "Cheltenham Town", country: "England", code: "CHE" },
  { id: 62, name: "Port Vale", country: "England", code: "PVL" },
  { id: 63, name: "Oxford United", country: "England", code: "OXF" },
  { id: 64, name: "Cambridge United", country: "England", code: "CAM" },
  { id: 65, name: "MK Dons", country: "England", code: "MKD" },
  { id: 66, name: "Accrington Stanley", country: "England", code: "ACC" },
  { id: 67, name: "Morecambe", country: "England", code: "MOR" },
  { id: 68, name: "Forest Green Rovers", country: "England", code: "FGR" },

  // England - League Two (2022/23)
  { id: 69, name: "Leyton Orient", country: "England", code: "LEY" },
  { id: 70, name: "Northampton Town", country: "England", code: "NOR" },
  { id: 71, name: "Stevenage", country: "England", code: "STE" },
  { id: 72, name: "Carlisle United", country: "England", code: "CRL" },
  { id: 73, name: "Stockport County", country: "England", code: "STO" },
  { id: 74, name: "Bradford City", country: "England", code: "BRA" },
  { id: 75, name: "Salford City", country: "England", code: "SAL" },
  { id: 76, name: "Mansfield Town", country: "England", code: "MAN" },
  { id: 77, name: "Barrow", country: "England", code: "BRW" },
  { id: 78, name: "Swindon Town", country: "England", code: "SWI" },
  { id: 79, name: "Grimsby Town", country: "England", code: "GRI" },
  { id: 80, name: "Tranmere Rovers", country: "England", code: "TRA" },
  { id: 81, name: "Crewe Alexandra", country: "England", code: "CRE" },
  { id: 82, name: "Sutton United", country: "England", code: "SUT" },
  { id: 83, name: "Newport County", country: "England", code: "NEW" },
  { id: 84, name: "Walsall", country: "England", code: "WAL" },
  { id: 85, name: "Doncaster Rovers", country: "England", code: "DON" },
  { id: 86, name: "Harrogate Town", country: "England", code: "HAR" },
  { id: 87, name: "Colchester United", country: "England", code: "COL" },
  { id: 88, name: "AFC Wimbledon", country: "England", code: "WIM" },
  { id: 89, name: "Crawley Town", country: "England", code: "CRA" },
  { id: 90, name: "Gillingham", country: "England", code: "GIL" },
  { id: 91, name: "Hartlepool United", country: "England", code: "HAR" },
  { id: 92, name: "Rochdale", country: "England", code: "ROC" },

  // Spain - LaLiga (2022/23)
  { id: 93, name: "Barcelona", country: "Spain", code: "BAR" },
  { id: 94, name: "Real Madrid", country: "Spain", code: "RMA" },
  { id: 95, name: "Atletico Madrid", country: "Spain", code: "ATM" },
  { id: 96, name: "Real Sociedad", country: "Spain", code: "RSO" },
  { id: 97, name: "Villarreal", country: "Spain", code: "VIL" },
  { id: 98, name: "Real Betis", country: "Spain", code: "BET" },
  { id: 99, name: "Osasuna", country: "Spain", code: "OSA" },
  { id: 100, name: "Athletic Bilbao", country: "Spain", code: "ATH" },
  { id: 101, name: "Mallorca", country: "Spain", code: "MAL" },
  { id: 102, name: "Girona", country: "Spain", code: "GIR" },
  { id: 103, name: "Rayo Vallecano", country: "Spain", code: "RAY" },
  { id: 104, name: "Sevilla", country: "Spain", code: "SEV" },
  { id: 105, name: "Celta Vigo", country: "Spain", code: "CEL" },
  { id: 106, name: "Cadiz", country: "Spain", code: "CAD" },
  { id: 107, name: "Getafe", country: "Spain", code: "GET" },
  { id: 108, name: "Valencia", country: "Spain", code: "VAL" },
  { id: 109, name: "Almeria", country: "Spain", code: "ALM" },
  { id: 110, name: "Valladolid", country: "Spain", code: "VLD" },
  { id: 111, name: "Espanyol", country: "Spain", code: "ESP" },
  { id: 112, name: "Elche", country: "Spain", code: "ELC" },

  // Spain - LaLiga 2 (2022/23)
  { id: 113, name: "Granada", country: "Spain", code: "GRA" },
  { id: 114, name: "Las Palmas", country: "Spain", code: "LPA" },
  { id: 115, name: "Levante", country: "Spain", code: "LEV" },
  { id: 116, name: "Alaves", country: "Spain", code: "ALA" },
  { id: 117, name: "Eibar", country: "Spain", code: "EIB" },
  { id: 118, name: "Burgos", country: "Spain", code: "BUR" },
  { id: 119, name: "Andorra", country: "Spain", code: "AND" },
  { id: 120, name: "Oviedo", country: "Spain", code: "OVI" },
  { id: 121, name: "Cartagena", country: "Spain", code: "CAR" },
  { id: 122, name: "Tenerife", country: "Spain", code: "TEN" },
  { id: 123, name: "Villarreal B", country: "Spain", code: "VIL" },
  { id: 124, name: "Huesca", country: "Spain", code: "HUE" },
  { id: 125, name: "Zaragoza", country: "Spain", code: "ZAR" },
  { id: 126, name: "Leganes", country: "Spain", code: "LEG" },
  { id: 127, name: "Mirandes", country: "Spain", code: "MIR" },
  { id: 128, name: "Ponferradina", country: "Spain", code: "PON" },
  { id: 129, name: "Malaga", country: "Spain", code: "MAL" },
  { id: 130, name: "Albacete", country: "Spain", code: "ALB" },
  { id: 131, name: "Lugo", country: "Spain", code: "LUG" },
  { id: 132, name: "Santander", country: "Spain", code: "RAC" },
  { id: 133, name: "Amorebieta", country: "Spain", code: "AMO" },
  { id: 134, name: "Ibiza", country: "Spain", code: "IBI" },

  // France - Ligue 1 (2022/23)
  { id: 135, name: "Paris Saint-Germain", country: "France", code: "PSG" },
  { id: 136, name: "Lens", country: "France", code: "LEN" },
  { id: 137, name: "Marseille", country: "France", code: "MAR" },
  { id: 138, name: "Rennes", country: "France", code: "REN" },
  { id: 139, name: "Lille", country: "France", code: "LIL" },
  { id: 140, name: "Monaco", country: "France", code: "MON" },
  { id: 141, name: "Lyon", country: "France", code: "LYO" },
  { id: 142, name: "Clermont Foot", country: "France", code: "CLE" },
  { id: 143, name: "Nice", country: "France", code: "NIC" },
  { id: 144, name: "Lorient", country: "France", code: "LOR" },
  { id: 145, name: "Reims", country: "France", code: "REI" },
  { id: 146, name: "Montpellier", country: "France", code: "MON" },
  { id: 147, name: "Toulouse", country: "France", code: "TOU" },
  { id: 148, name: "Brest", country: "France", code: "BRE" },
  { id: 149, name: "Strasbourg", country: "France", code: "STR" },
  { id: 150, name: "Nantes", country: "France", code: "NAN" },
  { id: 151, name: "Auxerre", country: "France", code: "AUX" },
  { id: 152, name: "Angers", country: "France", code: "ANG" },
  { id: 153, name: "Troyes", country: "France", code: "TRO" },
  { id: 154, name: "Ajaccio", country: "France", code: "AJA" },

  // France - Ligue 2 (2022/23)
  { id: 155, name: "Le Havre", country: "France", code: "LEH" },
  { id: 156, name: "Metz", country: "France", code: "MET" },
  { id: 157, name: "Bordeaux", country: "France", code: "BOR" },
  { id: 158, name: "Bastia", country: "France", code: "BAS" },
  { id: 159, name: "Grenoble", country: "France", code: "GRE" },
  { id: 160, name: "Caen", country: "France", code: "CAE" },
  { id: 161, name: "Paris FC", country: "France", code: "PAF" },
  { id: 162, name: "Guingamp", country: "France", code: "GUI" },
  { id: 163, name: "Saint-Etienne", country: "France", code: "ETI" },
  { id: 164, name: "Sochaux", country: "France", code: "SOC" },
  { id: 165, name: "Quevilly Rouen", country: "France", code: "QUE" },
  { id: 166, name: "Amiens", country: "France", code: "AMI" },
  { id: 167, name: "Valenciennes", country: "France", code: "VAL" },
  { id: 168, name: "Pau", country: "France", code: "PAU" },
  { id: 169, name: "Rodez", country: "France", code: "ROD" },
  { id: 170, name: "Laval", country: "France", code: "LAV" },
  { id: 171, name: "Annecy", country: "France", code: "ANN" },
  { id: 172, name: "Dijon", country: "France", code: "DIJ" },
  { id: 173, name: "Nimes", country: "France", code: "NIM" },
  { id: 174, name: "Niort", country: "France", code: "NIO" },

  // Germany - Bundesliga 1 (2022/23)
  { id: 175, name: "Bayern Munich", country: "Germany", code: "BAY" },
  { id: 176, name: "Borussia Dortmund", country: "Germany", code: "DOR" },
  { id: 177, name: "RB Leipzig", country: "Germany", code: "LEI" },
  { id: 178, name: "Union Berlin", country: "Germany", code: "UNI" },
  { id: 179, name: "Freiburg", country: "Germany", code: "FRE" },
  { id: 180, name: "Bayer Leverkusen", country: "Germany", code: "LEV" },
  { id: 181, name: "Eintracht Frankfurt", country: "Germany", code: "FRA" },
  { id: 182, name: "Wolfsburg", country: "Germany", code: "WOL" },
  { id: 183, name: "Mainz 05", country: "Germany", code: "MAI" },
  {
    id: 184,
    name: "Borussia Mönchengladbach",
    country: "Germany",
    code: "MGL",
  },
  { id: 185, name: "Köln", country: "Germany", code: "KOL" },
  { id: 186, name: "Hoffenheim", country: "Germany", code: "HOF" },
  { id: 187, name: "Werder Bremen", country: "Germany", code: "BRE" },
  { id: 188, name: "Bochum", country: "Germany", code: "BOC" },
  { id: 189, name: "Augsburg", country: "Germany", code: "AUG" },
  { id: 190, name: "Stuttgart", country: "Germany", code: "STU" },
  { id: 191, name: "Hertha Berlin", country: "Germany", code: "HER" },
  { id: 192, name: "Schalke 04", country: "Germany", code: "SCH" },

  // Germany - Bundesliga 2 (2022/23)
  { id: 193, name: "Hamburg", country: "Germany", code: "HAM" },
  { id: 194, name: "Heidenheim", country: "Germany", code: "HEI" },
  { id: 195, name: "Darmstadt", country: "Germany", code: "DAR" },
  { id: 196, name: "Fortuna Düsseldorf", country: "Germany", code: "DUS" },
  { id: 197, name: "St. Pauli", country: "Germany", code: "STP" },
  { id: 198, name: "Paderborn", country: "Germany", code: "PAD" },
  { id: 199, name: "Karlsruher", country: "Germany", code: "KAR" },
  { id: 200, name: "Greuther Fürth", country: "Germany", code: "FUR" },
  { id: 201, name: "Hannover 96", country: "Germany", code: "HAN" },
  { id: 202, name: "Nürnberg", country: "Germany", code: "NUR" },
  { id: 203, name: "Kaiserslautern", country: "Germany", code: "KAI" },
  { id: 204, name: "Holstein Kiel", country: "Germany", code: "KIE" },
  { id: 205, name: "Braunschweig", country: "Germany", code: "BRA" },
  { id: 206, name: "Hansa Rostock", country: "Germany", code: "ROS" },
  { id: 207, name: "Magdeburg", country: "Germany", code: "MAG" },
  { id: 208, name: "Sandhausen", country: "Germany", code: "SAN" },
  { id: 209, name: "Regensburg", country: "Germany", code: "REG" },
  { id: 210, name: "Bielefeld", country: "Germany", code: "BIE" },

  // Italy - Serie A (2022/23)
  { id: 211, name: "Napoli", country: "Italy", code: "NAP" },
  { id: 212, name: "Lazio", country: "Italy", code: "LAZ" },
  { id: 213, name: "Inter Milan", country: "Italy", code: "INT" },
  { id: 214, name: "AC Milan", country: "Italy", code: "MIL" },
  { id: 215, name: "Atalanta", country: "Italy", code: "ATA" },
  { id: 216, name: "Roma", country: "Italy", code: "ROM" },
  { id: 217, name: "Juventus", country: "Italy", code: "JUV" },
  { id: 218, name: "Fiorentina", country: "Italy", code: "FIO" },
  { id: 219, name: "Bologna", country: "Italy", code: "BOL" },
  { id: 220, name: "Torino", country: "Italy", code: "TOR" },
  { id: 221, name: "Monza", country: "Italy", code: "MON" },
  { id: 222, name: "Udinese", country: "Italy", code: "UDI" },
  { id: 223, name: "Sassuolo", country: "Italy", code: "SAS" },
  { id: 224, name: "Empoli", country: "Italy", code: "EMP" },
  { id: 225, name: "Salernitana", country: "Italy", code: "SAL" },
  { id: 226, name: "Lecce", country: "Italy", code: "LEC" },
  { id: 227, name: "Spezia", country: "Italy", code: "SPE" },
  { id: 228, name: "Hellas Verona", country: "Italy", code: "VER" },
  { id: 229, name: "Cremonese", country: "Italy", code: "CRE" },
  { id: 230, name: "Sampdoria", country: "Italy", code: "SAM" },

  // Italy - Serie B (2022/23)
  { id: 231, name: "Frosinone", country: "Italy", code: "FRO" },
  { id: 232, name: "Genoa", country: "Italy", code: "GEN" },
  { id: 233, name: "Bari", country: "Italy", code: "BAR" },
  { id: 234, name: "Cagliari", country: "Italy", code: "CAG" },
  { id: 235, name: "Parma", country: "Italy", code: "PAR" },
  { id: 236, name: "Sudtirol", country: "Italy", code: "SUD" },
  { id: 237, name: "Reggina", country: "Italy", code: "REG" },
  { id: 238, name: "Ternana", country: "Italy", code: "TER" },
  { id: 239, name: "Palermo", country: "Italy", code: "PAL" },
  { id: 240, name: "Modena", country: "Italy", code: "MOD" },
  { id: 241, name: "Como", country: "Italy", code: "COM" },
  { id: 242, name: "Ascoli", country: "Italy", code: "ASC" },
  { id: 243, name: "Cittadella", country: "Italy", code: "CIT" },
  { id: 244, name: "Pisa", country: "Italy", code: "PIS" },
  { id: 245, name: "Brescia", country: "Italy", code: "BRE" },
  { id: 246, name: "Perugia", country: "Italy", code: "PER" },
  { id: 247, name: "SPAL", country: "Italy", code: "SPA" },
  { id: 248, name: "Benevento", country: "Italy", code: "BEN" },
  { id: 249, name: "Venezia", country: "Italy", code: "VEN" },
  { id: 250, name: "Cosenza", country: "Italy", code: "COS" },

  // Netherlands - Eredivisie (2022/23)
  { id: 251, name: "Feyenoord", country: "Netherlands", code: "FEY" },
  { id: 252, name: "PSV Eindhoven", country: "Netherlands", code: "PSV" },
  { id: 253, name: "Ajax", country: "Netherlands", code: "AJX" },
  { id: 254, name: "AZ Alkmaar", country: "Netherlands", code: "AZ" },
  { id: 255, name: "Twente", country: "Netherlands", code: "TWE" },
  { id: 256, name: "Sparta Rotterdam", country: "Netherlands", code: "SPA" },
  { id: 257, name: "Utrecht", country: "Netherlands", code: "UTR" },
  { id: 258, name: "Heerenveen", country: "Netherlands", code: "HEE" },
  { id: 259, name: "NEC Nijmegen", country: "Netherlands", code: "NEC" },
  { id: 260, name: "Vitesse", country: "Netherlands", code: "VIT" },
  { id: 261, name: "Go Ahead Eagles", country: "Netherlands", code: "GAE" },
  { id: 262, name: "Fortuna Sittard", country: "Netherlands", code: "FOR" },
  { id: 263, name: "Groningen", country: "Netherlands", code: "GRO" },
  { id: 264, name: "Cambuur", country: "Netherlands", code: "CAM" },
  { id: 265, name: "Waalwijk", country: "Netherlands", code: "WAA" },
  { id: 266, name: "Excelsior", country: "Netherlands", code: "EXC" },
  { id: 267, name: "Volendam", country: "Netherlands", code: "VOL" },
  { id: 268, name: "Emmen", country: "Netherlands", code: "EMM" },

  // Netherlands - Eerste Divisie (2022/23)
  { id: 269, name: "Heracles", country: "Netherlands", code: "HER" },
  { id: 270, name: "PEC Zwolle", country: "Netherlands", code: "ZWO" },
  { id: 271, name: "Almere City", country: "Netherlands", code: "ALM" },
  { id: 272, name: "Willem II", country: "Netherlands", code: "WIL" },
  { id: 273, name: "MVV Maastricht", country: "Netherlands", code: "MVV" },
  { id: 274, name: "VVV-Venlo", country: "Netherlands", code: "VVV" },
  { id: 275, name: "Telstar", country: "Netherlands", code: "TEL" },
  { id: 276, name: "De Graafschap", country: "Netherlands", code: "GRA" },
  { id: 277, name: "ADO Den Haag", country: "Netherlands", code: "ADO" },
  { id: 278, name: "FC Eindhoven", country: "Netherlands", code: "EIN" },
  { id: 279, name: "Jong Ajax", country: "Netherlands", code: "JAX" },
  { id: 280, name: "Jong PSV", country: "Netherlands", code: "JPS" },
  { id: 281, name: "Dordrecht", country: "Netherlands", code: "DOR" },
  { id: 282, name: "Helmond Sport", country: "Netherlands", code: "HEL" },
  { id: 283, name: "NAC Breda", country: "Netherlands", code: "NAC" },
  { id: 284, name: "Roda JC", country: "Netherlands", code: "ROD" },
  { id: 285, name: "Jong Utrecht", country: "Netherlands", code: "JUT" },
  { id: 286, name: "TOP Oss", country: "Netherlands", code: "OSS" },
  { id: 287, name: "Jong AZ", country: "Netherlands", code: "JAZ" },

  // Portugal - Primeira Liga (2022/23)
  { id: 288, name: "Benfica", country: "Portugal", code: "BEN" },
  { id: 289, name: "Porto", country: "Portugal", code: "POR" },
  { id: 290, name: "Braga", country: "Portugal", code: "BRA" },
  { id: 291, name: "Sporting CP", country: "Portugal", code: "SPO" },
  { id: 292, name: "Arouca", country: "Portugal", code: "ARO" },
  { id: 293, name: "Vitoria Guimaraes", country: "Portugal", code: "VIT" },
  { id: 294, name: "Chaves", country: "Portugal", code: "CHA" },
  { id: 295, name: "Famalicao", country: "Portugal", code: "FAM" },
  { id: 296, name: "Casa Pia", country: "Portugal", code: "CAS" },
  { id: 297, name: "Boavista", country: "Portugal", code: "BOA" },
  { id: 298, name: "Vizela", country: "Portugal", code: "VIZ" },
  { id: 299, name: "Rio Ave", country: "Portugal", code: "RIO" },
  { id: 300, name: "Gil Vicente", country: "Portugal", code: "GIL" },
  { id: 301, name: "Estoril", country: "Portugal", code: "EST" },
  { id: 302, name: "Portimonense", country: "Portugal", code: "PTM" },
  { id: 303, name: "Maritimo", country: "Portugal", code: "MAR" },
  { id: 304, name: "Pacos de Ferreira", country: "Portugal", code: "PAC" },
  { id: 305, name: "Santa Clara", country: "Portugal", code: "SAN" },

  // Belgium - Pro League (2022/23)
  { id: 306, name: "Genk", country: "Belgium", code: "GNK" },
  { id: 307, name: "Union SG", country: "Belgium", code: "USG" },
  { id: 308, name: "Antwerp", country: "Belgium", code: "ANT" },
  { id: 309, name: "Club Brugge", country: "Belgium", code: "BRU" },
  { id: 310, name: "Gent", country: "Belgium", code: "GEN" },
  { id: 311, name: "Standard Liège", country: "Belgium", code: "STD" },
  { id: 312, name: "Westerlo", country: "Belgium", code: "WES" },
  { id: 313, name: "Cercle Brugge", country: "Belgium", code: "CER" },
  { id: 314, name: "Charleroi", country: "Belgium", code: "CHA" },
  { id: 315, name: "OH Leuven", country: "Belgium", code: "LEU" },
  { id: 316, name: "Anderlecht", country: "Belgium", code: "AND" },
  { id: 317, name: "Mechelen", country: "Belgium", code: "MEC" },
  { id: 318, name: "Kortrijk", country: "Belgium", code: "KOR" },
  { id: 319, name: "Eupen", country: "Belgium", code: "EUP" },
  { id: 320, name: "Seraing", country: "Belgium", code: "SER" },
  { id: 321, name: "Oostende", country: "Belgium", code: "OOS" },
  { id: 322, name: "Zulte Waregem", country: "Belgium", code: "ZUL" },

  // Denmark - Superliga (2022/23)
  { id: 323, name: "Copenhagen", country: "Denmark", code: "COP" },
  { id: 324, name: "Silkeborg", country: "Denmark", code: "SIL" },
  { id: 325, name: "Viborg", country: "Denmark", code: "VIB" },
  { id: 326, name: "AGF", country: "Denmark", code: "AGF" },
  { id: 327, name: "Randers", country: "Denmark", code: "RAN" },
  { id: 328, name: "Nordsjælland", country: "Denmark", code: "NOR" },
  { id: 329, name: "Brøndby", country: "Denmark", code: "BRO" },
  { id: 330, name: "Midtjylland", country: "Denmark", code: "MID" },
  { id: 331, name: "OB", country: "Denmark", code: "OB" },
  { id: 332, name: "Lyngby", country: "Denmark", code: "LYN" },
  { id: 333, name: "Horsens", country: "Denmark", code: "HOR" },
  { id: 334, name: "Aalborg", country: "Denmark", code: "AAB" },

  // Denmark - 1st Division (2022/23)
  { id: 335, name: "Hvidovre", country: "Denmark", code: "HVI" },
  { id: 336, name: "Fredericia", country: "Denmark", code: "FRE" },
  { id: 337, name: "Hillerød", country: "Denmark", code: "HIL" },
  { id: 338, name: "Kolding", country: "Denmark", code: "KOL" },
  { id: 339, name: "HB Køge", country: "Denmark", code: "HBK" },
  { id: 340, name: "Vendsyssel", country: "Denmark", code: "VEN" },
  { id: 341, name: "B93", country: "Denmark", code: "B93" },
  { id: 342, name: "Fremad Amager", country: "Denmark", code: "FRE" },
  { id: 343, name: "Hobro", country: "Denmark", code: "HOB" },
  { id: 344, name: "Næstved", country: "Denmark", code: "NAS" },
  { id: 345, name: "Roskilde", country: "Denmark", code: "ROS" },

  // Australia - A-League (2022/23)
  { id: 346, name: "Melbourne City", country: "Australia", code: "MCY" },
  {
    id: 347,
    name: "Central Coast Mariners",
    country: "Australia",
    code: "CCM",
  },
  { id: 348, name: "Adelaide United", country: "Australia", code: "ADL" },
  { id: 349, name: "Western Sydney", country: "Australia", code: "WSW" },
  { id: 350, name: "Sydney FC", country: "Australia", code: "SYD" },
  { id: 351, name: "Wellington Phoenix", country: "Australia", code: "WEL" },
  { id: 352, name: "Western United", country: "Australia", code: "WUN" },
  { id: 353, name: "Brisbane Roar", country: "Australia", code: "BRI" },
  { id: 354, name: "Newcastle Jets", country: "Australia", code: "NEW" },
  { id: 355, name: "Macarthur FC", country: "Australia", code: "MAC" },
  { id: 356, name: "Perth Glory", country: "Australia", code: "PER" },
  { id: 357, name: "Melbourne Victory", country: "Australia", code: "MVI" },

  // Australia - A-League 2 (2022/23)
  { id: 358, name: "Bulls FC Academy", country: "Australia", code: "BUL" },
  { id: 359, name: "Marconi Stallions", country: "Australia", code: "MAR" },
  { id: 360, name: "APIA Leichhardt", country: "Australia", code: "API" },
  { id: 361, name: "Sydney Olympic", country: "Australia", code: "OLY" },
  { id: 362, name: "Blacktown City", country: "Australia", code: "BLA" },
  { id: 363, name: "Rockdale Ilinden", country: "Australia", code: "ROC" },
  { id: 364, name: "Manly United", country: "Australia", code: "MAN" },
  { id: 365, name: "Sydney United 58", country: "Australia", code: "SU5" },
  { id: 366, name: "Wollongong Wolves", country: "Australia", code: "WOL" },
  { id: 367, name: "Sutherland Sharks", country: "Australia", code: "SUT" },

  // Greece - Super League 1 (2022/23)
  { id: 368, name: "Olympiacos", country: "Greece", code: "OLY" },
  { id: 369, name: "Panathinaikos", country: "Greece", code: "PAN" },
  { id: 370, name: "AEK Athens", country: "Greece", code: "AEK" },
  { id: 371, name: "PAOK", country: "Greece", code: "PAO" },
  { id: 372, name: "Aris", country: "Greece", code: "ARI" },
  { id: 373, name: "Volos", country: "Greece", code: "VOL" },
  { id: 374, name: "OFI Crete", country: "Greece", code: "OFI" },
  { id: 375, name: "Atromitos", country: "Greece", code: "ATR" },
  { id: 376, name: "Panetolikos", country: "Greece", code: "PET" },
  { id: 377, name: "Asteras Tripolis", country: "Greece", code: "AST" },
  { id: 378, name: "Ionikos", country: "Greece", code: "ION" },
  { id: 379, name: "Levadiakos", country: "Greece", code: "LEV" },
  { id: 380, name: "Lamia", country: "Greece", code: "LAM" },

  // Romania - Liga 1 (2022/23)
  { id: 381, name: "Farul Constanța", country: "Romania", code: "FAR" },
  { id: 382, name: "CFR Cluj", country: "Romania", code: "CFR" },
  { id: 383, name: "FCSB", country: "Romania", code: "FCS" },
  { id: 384, name: "Rapid București", country: "Romania", code: "RAP" },
  { id: 385, name: "Universitatea Craiova", country: "Romania", code: "UCR" },
  { id: 386, name: "Sepsi Sfântu Gheorghe", country: "Romania", code: "SEP" },
  { id: 387, name: "FC U Craiova 1948", country: "Romania", code: "UC8" },
  { id: 388, name: "Petrolul Ploiești", country: "Romania", code: "PET" },
  { id: 389, name: "Hermannstadt", country: "Romania", code: "HER" },
  { id: 390, name: "Argeș Pitești", country: "Romania", code: "ARG" },
  { id: 391, name: "Mioveni", country: "Romania", code: "MIO" },
  { id: 392, name: "Botoșani", country: "Romania", code: "BOT" },
  { id: 393, name: "Chindia Târgoviște", country: "Romania", code: "CHI" },
  { id: 394, name: "Voluntari", country: "Romania", code: "VOL" },
  { id: 395, name: "UTA Arad", country: "Romania", code: "UTA" },

  // Sweden - Allsvenskan (2022)
  { id: 396, name: "BK Häcken", country: "Sweden", code: "HAC" },
  { id: 397, name: "Djurgårdens IF", country: "Sweden", code: "DIF" },
  { id: 398, name: "Hammarby IF", country: "Sweden", code: "HAM" },
  { id: 399, name: "Kalmar FF", country: "Sweden", code: "KAL" },
  { id: 400, name: "AIK", country: "Sweden", code: "AIK" },
  { id: 401, name: "IF Elfsborg", country: "Sweden", code: "ELF" },
  { id: 402, name: "IFK Norrköping", country: "Sweden", code: "NOR" },
  { id: 403, name: "Malmö FF", country: "Sweden", code: "MAL" },
  { id: 404, name: "IFK Göteborg", country: "Sweden", code: "GOT" },
  { id: 405, name: "Mjällby AIF", country: "Sweden", code: "MJA" },
  { id: 406, name: "IK Sirius", country: "Sweden", code: "SIR" },
  { id: 407, name: "Varbergs BoIS", country: "Sweden", code: "VAR" },
  { id: 408, name: "Degerfors IF", country: "Sweden", code: "DEG" },
  { id: 409, name: "Helsingborgs IF", country: "Sweden", code: "HEL" },
  { id: 410, name: "GIF Sundsvall", country: "Sweden", code: "SUN" },
  { id: 411, name: "IFK Värnamo", country: "Sweden", code: "VAR" },

  // Sweden - Superettan (2022)
  { id: 412, name: "Halmstads BK", country: "Sweden", code: "HAL" },
  { id: 413, name: "Östers IF", country: "Sweden", code: "OST" },
  { id: 414, name: "Örebro SK", country: "Sweden", code: "ORE" },
  { id: 415, name: "Landskrona BoIS", country: "Sweden", code: "LAN" },
  { id: 416, name: "Örgryte IS", country: "Sweden", code: "ORG" },
  { id: 417, name: "GAIS", country: "Sweden", code: "GAI" },
  { id: 418, name: "Trelleborgs FF", country: "Sweden", code: "TRE" },
  { id: 419, name: "AFC Eskilstuna", country: "Sweden", code: "AFE" },
  { id: 420, name: "IK Brage", country: "Sweden", code: "BRA" },
  { id: 421, name: "Jönköpings Södra", country: "Sweden", code: "JON" },
  { id: 422, name: "Norrby IF", country: "Sweden", code: "NOR" },
  { id: 423, name: "Västerås SK", country: "Sweden", code: "VAS" },
  { id: 424, name: "Gefle IF", country: "Sweden", code: "GEF" },
  { id: 425, name: "Falkenbergs FF", country: "Sweden", code: "FAL" },
  { id: 426, name: "Utsiktens BK", country: "Sweden", code: "UTS" },
  { id: 427, name: "Skövde AIK", country: "Sweden", code: "SKO" },

  // Turkey - Süper Lig (2022/23)
  { id: 428, name: "Galatasaray", country: "Turkey", code: "GAL" },
  { id: 429, name: "Fenerbahçe", country: "Turkey", code: "FEN" },
  { id: 430, name: "Beşiktaş", country: "Turkey", code: "BES" },
  { id: 431, name: "Adana Demirspor", country: "Turkey", code: "ADA" },
  { id: 432, name: "Trabzonspor", country: "Turkey", code: "TRA" },
  { id: 433, name: "Konyaspor", country: "Turkey", code: "KON" },
  { id: 434, name: "Kayserispor", country: "Turkey", code: "KAY" },
  { id: 435, name: "İstanbul Başakşehir", country: "Turkey", code: "BAS" },
  { id: 436, name: "Alanyaspor", country: "Turkey", code: "ALA" },
  { id: 437, name: "Fatih Karagümrük", country: "Turkey", code: "KAR" },
  { id: 438, name: "Kasımpaşa", country: "Turkey", code: "KAS" },
  { id: 439, name: "Antalyaspor", country: "Turkey", code: "ANT" },
  { id: 440, name: "Gaziantep FK", country: "Turkey", code: "GAZ" },
  { id: 441, name: "Sivasspor", country: "Turkey", code: "SIV" },
  { id: 442, name: "Hatayspor", country: "Turkey", code: "HAT" },
  { id: 443, name: "Giresunspor", country: "Turkey", code: "GIR" },
  { id: 444, name: "Ankaragücü", country: "Turkey", code: "ANK" },
  { id: 445, name: "Ümraniyespor", country: "Turkey", code: "UMR" },
  { id: 446, name: "İstanbulspor", country: "Turkey", code: "IST" },

  // Norway - Eliteserien (2022)
  { id: 447, name: "Bodø/Glimt", country: "Norway", code: "BOD" },
  { id: 448, name: "Molde", country: "Norway", code: "MOL" },
  { id: 449, name: "Rosenborg", country: "Norway", code: "ROS" },
  { id: 450, name: "Lillestrøm", country: "Norway", code: "LIL" },
  { id: 451, name: "Odd", country: "Norway", code: "ODD" },
  { id: 452, name: "Vålerenga", country: "Norway", code: "VAL" },
  { id: 453, name: "Tromsø", country: "Norway", code: "TRO" },
  { id: 454, name: "Sarpsborg 08", country: "Norway", code: "SAR" },
  { id: 455, name: "Aalesund", country: "Norway", code: "AAL" },
  { id: 456, name: "Strømsgodset", country: "Norway", code: "STR" },
  { id: 457, name: "Haugesund", country: "Norway", code: "HAU" },
  { id: 458, name: "Viking", country: "Norway", code: "VIK" },
  { id: 459, name: "Sandefjord", country: "Norway", code: "SAN" },
  { id: 460, name: "HamKam", country: "Norway", code: "HAM" },
  { id: 461, name: "Jerv", country: "Norway", code: "JER" },
  { id: 462, name: "Kristiansund", country: "Norway", code: "KRI" },

  // Norway - OBOS-ligaen (2022)
  { id: 463, name: "Brann", country: "Norway", code: "BRA" },
  { id: 464, name: "Stabæk", country: "Norway", code: "STA" },
  { id: 465, name: "Start", country: "Norway", code: "STA" },
  { id: 466, name: "Kongsvinger", country: "Norway", code: "KON" },
  { id: 467, name: "Ranheim", country: "Norway", code: "RAN" },
  { id: 468, name: "Sogndal", country: "Norway", code: "SOG" },
  { id: 469, name: "Mjøndalen", country: "Norway", code: "MJO" },
  { id: 470, name: "Fredrikstad", country: "Norway", code: "FRE" },
  { id: 471, name: "Bryne", country: "Norway", code: "BRY" },
  { id: 472, name: "Raufoss", country: "Norway", code: "RAU" },
  { id: 473, name: "Åsane", country: "Norway", code: "ASA" },
  { id: 474, name: "Sandnes Ulf", country: "Norway", code: "ULF" },
  { id: 475, name: "Grorud", country: "Norway", code: "GRO" },
  { id: 476, name: "Stjørdals-Blink", country: "Norway", code: "STJ" },
  { id: 477, name: "KFUM Oslo", country: "Norway", code: "KFU" },
  { id: 478, name: "Skeid", country: "Norway", code: "SKE" },

  // Japan - J1 League (2022)
  { id: 479, name: "Yokohama F. Marinos", country: "Japan", code: "YFM" },
  { id: 480, name: "Kawasaki Frontale", country: "Japan", code: "KAW" },
  { id: 481, name: "Sanfrecce Hiroshima", country: "Japan", code: "SAN" },
  { id: 482, name: "Kashima Antlers", country: "Japan", code: "KAS" },
  { id: 483, name: "Tokyo", country: "Japan", code: "FCT" },
  { id: 484, name: "Nagoya Grampus", country: "Japan", code: "NAG" },
  { id: 485, name: "Urawa Reds", country: "Japan", code: "URA" },
  { id: 486, name: "Cerezo Osaka", country: "Japan", code: "CER" },
  { id: 487, name: "Consadole Sapporo", country: "Japan", code: "CON" },
  { id: 488, name: "Shonan Bellmare", country: "Japan", code: "SHO" },
  { id: 489, name: "Gamba Osaka", country: "Japan", code: "GAM" },
  { id: 490, name: "Kashiwa Reysol", country: "Japan", code: "KAS" },
  { id: 491, name: "Kyoto Sanga", country: "Japan", code: "KYO" },
  { id: 492, name: "Sagan Tosu", country: "Japan", code: "SAG" },
  { id: 493, name: "Avispa Fukuoka", country: "Japan", code: "AVI" },
  { id: 494, name: "Vissel Kobe", country: "Japan", code: "VIS" },
  { id: 495, name: "Shimizu S-Pulse", country: "Japan", code: "SHI" },
  { id: 496, name: "Júbilo Iwata", country: "Japan", code: "JUB" },
  { id: 497, name: "Vegalta Sendai", country: "Japan", code: "VEG" },

  // South Korea - K League 1 (2022)
  { id: 498, name: "Ulsan Hyundai", country: "South Korea", code: "ULS" },
  { id: 499, name: "Jeonbuk Hyundai", country: "South Korea", code: "JEO" },
  { id: 500, name: "Pohang Steelers", country: "South Korea", code: "POH" },
  { id: 501, name: "Incheon United", country: "South Korea", code: "INC" },
  { id: 502, name: "Jeju United", country: "South Korea", code: "JEJ" },
  { id: 503, name: "Suwon Samsung", country: "South Korea", code: "SUW" },
  { id: 504, name: "Daegu FC", country: "South Korea", code: "DAE" },
  { id: 505, name: "Seoul", country: "South Korea", code: "SEO" },
  { id: 506, name: "Gwangju FC", country: "South Korea", code: "GWA" },
  { id: 507, name: "Suwon FC", country: "South Korea", code: "SUF" },
  { id: 508, name: "Gangwon FC", country: "South Korea", code: "GAN" },
  { id: 509, name: "Seongnam FC", country: "South Korea", code: "SEG" },

  // UAE - Pro League (2022/23)
  { id: 510, name: "Al Ain", country: "UAE", code: "AIN" },
  { id: 511, name: "Al Wasl", country: "UAE", code: "WAS" },
  { id: 512, name: "Sharjah", country: "UAE", code: "SHR" },
  { id: 513, name: "Al Wahda", country: "UAE", code: "WAH" },
  { id: 514, name: "Al Jazira", country: "UAE", code: "JAZ" },
  { id: 515, name: "Baniyas", country: "UAE", code: "BAN" },
  { id: 516, name: "Ajman", country: "UAE", code: "AJM" },
  { id: 517, name: "Al Nasr", country: "UAE", code: "NAS" },
  { id: 518, name: "Al Dhafra", country: "UAE", code: "DHA" },
  { id: 519, name: "Khor Fakkan", country: "UAE", code: "KHO" },
  { id: 520, name: "Ittihad Kalba", country: "UAE", code: "KAL" },
  { id: 521, name: "Dibba Al Fujairah", country: "UAE", code: "DIB" },

  // Thailand - Thai League 1 (2022/23)
  { id: 522, name: "Buriram United", country: "Thailand", code: "BUR" },
  { id: 523, name: "BG Pathum United", country: "Thailand", code: "BGP" },
  { id: 524, name: "Port FC", country: "Thailand", code: "POR" },
  { id: 525, name: "Muangthong United", country: "Thailand", code: "MTU" },
  { id: 526, name: "Chonburi FC", country: "Thailand", code: "CHO" },
  { id: 527, name: "Ratchaburi FC", country: "Thailand", code: "RAT" },
  { id: 528, name: "Bangkok United", country: "Thailand", code: "BKU" },
  { id: 529, name: "Nakhon Ratchasima", country: "Thailand", code: "NRM" },
  { id: 530, name: "PT Prachuap FC", country: "Thailand", code: "PRA" },
  { id: 531, name: "Khonkaen United", country: "Thailand", code: "KKU" },
  { id: 532, name: "Suphanburi FC", country: "Thailand", code: "SUP" },
  { id: 533, name: "Nongbua Pitchaya", country: "Thailand", code: "NON" },
  { id: 534, name: "Lamphun Warriors", country: "Thailand", code: "LAM" },
  { id: 535, name: "Sukhothai FC", country: "Thailand", code: "SUK" },
  { id: 536, name: "Lampang FC", country: "Thailand", code: "LPG" },
  { id: 537, name: "Police Tero FC", country: "Thailand", code: "TER" },
  { id: 538, name: "Samut Prakan City", country: "Thailand", code: "SAM" },
  { id: 539, name: "Uthai Thani FC", country: "Thailand", code: "UTT" },

  // Brazil - Série A (2022)
  { id: 540, name: "Palmeiras", country: "Brazil", code: "PAL" },
  { id: 541, name: "Internacional", country: "Brazil", code: "INT" },
  { id: 542, name: "Fluminense", country: "Brazil", code: "FLU" },
  { id: 543, name: "Corinthians", country: "Brazil", code: "COR" },
  { id: 544, name: "Flamengo", country: "Brazil", code: "FLA" },
  { id: 545, name: "Athletico-PR", country: "Brazil", code: "CAP" },
  { id: 546, name: "Atlético Mineiro", country: "Brazil", code: "CAM" },
  { id: 547, name: "São Paulo", country: "Brazil", code: "SAO" },
  { id: 548, name: "América-MG", country: "Brazil", code: "AMG" },
  { id: 549, name: "Botafogo", country: "Brazil", code: "BOT" },
  { id: 550, name: "Santos", country: "Brazil", code: "SAN" },
  { id: 551, name: "Goiás", country: "Brazil", code: "GOI" },
  { id: 552, name: "Bragantino", country: "Brazil", code: "RBB" },
  { id: 553, name: "Fortaleza", country: "Brazil", code: "FOR" },
  { id: 554, name: "Ceará", country: "Brazil", code: "CEA" },
  { id: 555, name: "Cuiabá", country: "Brazil", code: "CUI" },
  { id: 556, name: "Avaí", country: "Brazil", code: "AVA" },
  { id: 557, name: "Coritiba", country: "Brazil", code: "CFC" },
  { id: 558, name: "Atlético Goianiense", country: "Brazil", code: "ACG" },
  { id: 559, name: "Juventude", country: "Brazil", code: "JUV" },

  // Argentina - Liga Profesional (2022)
  { id: 560, name: "Boca Juniors", country: "Argentina", code: "BOC" },
  { id: 561, name: "River Plate", country: "Argentina", code: "RIV" },
  { id: 562, name: "Racing Club", country: "Argentina", code: "RAC" },
  { id: 563, name: "Huracán", country: "Argentina", code: "HUR" },
  { id: 564, name: "Atlético Tucumán", country: "Argentina", code: "ATU" },
  { id: 565, name: "San Lorenzo", country: "Argentina", code: "SLO" },
  { id: 566, name: "Gimnasia La Plata", country: "Argentina", code: "GIM" },
  { id: 567, name: "Argentinos Juniors", country: "Argentina", code: "ARG" },
  { id: 568, name: "Rosario Central", country: "Argentina", code: "ROS" },
  { id: 569, name: "Estudiantes", country: "Argentina", code: "EST" },
  { id: 570, name: "Defensa y Justicia", country: "Argentina", code: "DYJ" },
  { id: 571, name: "Platense", country: "Argentina", code: "PLA" },
  { id: 572, name: "Newell's Old Boys", country: "Argentina", code: "NEW" },
  { id: 573, name: "Talleres", country: "Argentina", code: "TAL" },
  { id: 574, name: "Banfield", country: "Argentina", code: "BAN" },
  { id: 575, name: "Lanús", country: "Argentina", code: "LAN" },
  { id: 576, name: "Unión Santa Fe", country: "Argentina", code: "UNI" },
  { id: 577, name: "Barracas Central", country: "Argentina", code: "BAR" },
  { id: 578, name: "Sarmiento", country: "Argentina", code: "SAR" },
  { id: 579, name: "Central Córdoba", country: "Argentina", code: "CCO" },
  { id: 580, name: "Arsenal Sarandí", country: "Argentina", code: "ARS" },
  { id: 581, name: "Colón", country: "Argentina", code: "COL" },
  { id: 582, name: "Patronato", country: "Argentina", code: "PAT" },
  { id: 583, name: "Vélez Sarsfield", country: "Argentina", code: "VEL" },
  { id: 584, name: "Independiente", country: "Argentina", code: "IND" },
  { id: 585, name: "Godoy Cruz", country: "Argentina", code: "GOD" },
  { id: 586, name: "Tigre", country: "Argentina", code: "TIG" },
  { id: 587, name: "Aldosivi", country: "Argentina", code: "ALD" },

  // Mexican Liga MX Season 2023-2024
  { id: 588, team: "América", country: "Mexico", code: "MEX_AME" },
  { id: 589, team: "Guadalajara", country: "Mexico", code: "MEX_CHV" },
  { id: 590, team: "Cruz Azul", country: "Mexico", code: "MEX_CAZ" },
  { id: 591, team: "Monterrey", country: "Mexico", code: "MEX_MTY" },
  { id: 592, team: "Tigres UANL", country: "Mexico", code: "MEX_TIG" },
  { id: 593, team: "Pumas UNAM", country: "Mexico", code: "MEX_UNM" },
  { id: 594, team: "León", country: "Mexico", code: "MEX_LEO" },
  { id: 595, team: "Pachuca", country: "Mexico", code: "MEX_PAC" },
  { id: 596, team: "Santos Laguna", country: "Mexico", code: "MEX_SAN" },
  { id: 597, team: "Toluca", country: "Mexico", code: "MEX_TOL" },
  { id: 598, team: "Atlas", country: "Mexico", code: "MEX_ATL" },
  { id: 599, team: "Atlético San Luis", country: "Mexico", code: "MEX_ASL" },
  { id: 600, team: "FC Juárez", country: "Mexico", code: "MEX_JUA" },
  { id: 601, team: "Tijuana", country: "Mexico", code: "MEX_TIJ" },
  { id: 602, team: "Necaxa", country: "Mexico", code: "MEX_NEC" },
  { id: 603, team: "Puebla", country: "Mexico", code: "MEX_PUE" },
  { id: 604, team: "Mazatlán", country: "Mexico", code: "MEX_MAZ" },
  { id: 605, team: "Querétaro", country: "Mexico", code: "MEX_QUE" },

  // Scottish Premiership Season 2023-2024
  { id: 606, team: "Celtic", country: "Scotland", code: "SCO_CEL" },
  { id: 607, team: "Rangers", country: "Scotland", code: "SCO_RAN" },
  {
    id: 608,
    team: "Heart of Midlothian",
    country: "Scotland",
    code: "SCO_HEA",
  },
  { id: 609, team: "Hibernian", country: "Scotland", code: "SCO_HIB" },
  { id: 610, team: "Aberdeen", country: "Scotland", code: "SCO_ABE" },
  { id: 611, team: "Livingston", country: "Scotland", code: "SCO_LIV" },
  { id: 612, team: "St. Johnstone", country: "Scotland", code: "SCO_STJ" },
  { id: 613, team: "Dundee United", country: "Scotland", code: "SCO_DUN" },
  { id: 614, team: "Motherwell", country: "Scotland", code: "SCO_MOT" },
  { id: 615, team: "St. Mirren", country: "Scotland", code: "SCO_STM" },
  { id: 616, team: "Ross County", country: "Scotland", code: "SCO_ROS" },
  { id: 617, team: "Kilmarnock", country: "Scotland", code: "SCO_KIL" },

  // Finnish Veikkausliiga Season 2023
  { id: 618, team: "HJK Helsinki", country: "Finland", code: "FIN_HJK" },
  { id: 619, team: "KuPS", country: "Finland", code: "FIN_KPS" },
  { id: 620, team: "Honka", country: "Finland", code: "FIN_HON" },
  { id: 621, team: "Ilves", country: "Finland", code: "FIN_ILV" },
  { id: 622, team: "SJK", country: "Finland", code: "FIN_SJK" },
  { id: 623, team: "Lahti", country: "Finland", code: "FIN_LAH" },
  { id: 624, team: "HIFK", country: "Finland", code: "FIN_HIF" },
  { id: 625, team: "AC Oulu", country: "Finland", code: "FIN_AOU" },
  { id: 626, team: "Inter Turku", country: "Finland", code: "FIN_INT" },
  { id: 627, team: "VPS", country: "Finland", code: "FIN_VPS" },
  { id: 628, team: "IFK Mariehamn", country: "Finland", code: "FIN_IFK" },
  { id: 629, team: "FC Haka", country: "Finland", code: "FIN_HAK" },

  // Austrian Bundesliga Season 2023-2024
  { id: 630, team: "Red Bull Salzburg", country: "Austria", code: "AUT_RBS" },
  { id: 631, team: "Sturm Graz", country: "Austria", code: "AUT_STU" },
  { id: 632, team: "LASK", country: "Austria", code: "AUT_LAS" },
  { id: 633, team: "Austria Wien", country: "Austria", code: "AUT_AWI" },
  { id: 634, team: "Rapid Wien", country: "Austria", code: "AUT_RAP" },
  { id: 635, team: "Wolfsberger AC", country: "Austria", code: "AUT_WAC" },
  { id: 636, team: "Hartberg", country: "Austria", code: "AUT_HAR" },
  { id: 637, team: "Austria Klagenfurt", country: "Austria", code: "AUT_AKL" },
  { id: 638, team: "Rheindorf Altach", country: "Austria", code: "AUT_ALT" },
  { id: 639, team: "WSG Tirol", country: "Austria", code: "AUT_WTI" },
  { id: 640, team: "Blau-Weiß Linz", country: "Austria", code: "AUT_BWL" },
  { id: 641, team: "SV Ried", country: "Austria", code: "AUT_RIE" },

  // League of Ireland Premier Division Season 2023
  { id: 642, team: "Shamrock Rovers", country: "Ireland", code: "IRL_SHA" },
  { id: 643, team: "Derry City", country: "Ireland", code: "IRL_DER" },
  {
    id: 644,
    team: "St Patrick's Athletic",
    country: "Ireland",
    code: "IRL_STP",
  },
  { id: 645, team: "Dundalk", country: "Ireland", code: "IRL_DUN" },
  { id: 646, team: "Bohemian", country: "Ireland", code: "IRL_BOH" },
  { id: 647, team: "Sligo Rovers", country: "Ireland", code: "IRL_SLI" },
  { id: 648, team: "Shelbourne", country: "Ireland", code: "IRL_SHE" },
  { id: 649, team: "UCD", country: "Ireland", code: "IRL_UCD" },
  { id: 650, team: "Drogheda United", country: "Ireland", code: "IRL_DRO" },
  { id: 651, team: "Cork City", country: "Ireland", code: "IRL_COR" },

  // Polish Ekstraklasa Season 2023-2024
  { id: 652, team: "Raków Częstochowa", country: "Poland", code: "POL_RAC" },
  { id: 653, team: "Legia Warsaw", country: "Poland", code: "POL_LEG" },
  { id: 654, team: "Lech Poznań", country: "Poland", code: "POL_LPO" },
  { id: 655, team: "Pogoń Szczecin", country: "Poland", code: "POL_POG" },
  { id: 656, team: "Piast Gliwice", country: "Poland", code: "POL_PIA" },
  { id: 657, team: "Górnik Zabrze", country: "Poland", code: "POL_GOR" },
  { id: 658, team: "Cracovia", country: "Poland", code: "POL_CRA" },
  { id: 659, team: "Warta Poznań", country: "Poland", code: "POL_WAR" },
  { id: 660, team: "Zagłębie Lubin", country: "Poland", code: "POL_ZAG" },
  { id: 661, team: "Śląsk Wrocław", country: "Poland", code: "POL_SLA" },
  { id: 662, team: "Stal Mielec", country: "Poland", code: "POL_STM" },
  { id: 663, team: "Widzew Łódź", country: "Poland", code: "POL_WID" },
  {
    id: 664,
    team: "Jagiellonia Białystok",
    country: "Poland",
    code: "POL_JAG",
  },
  { id: 665, team: "Korona Kielce", country: "Poland", code: "POL_KOR" },
  { id: 666, team: "Radomiak Radom", country: "Poland", code: "POL_RAD" },
  { id: 667, team: "Puszcza Niepołomice", country: "Poland", code: "POL_PUS" },
  { id: 668, team: "Ruch Chorzów", country: "Poland", code: "POL_RUC" },
  { id: 669, team: "ŁKS Łódź", country: "Poland", code: "POL_LKS" },

  // Russian Premier League Season 2023-2024 (Subject to change)
  {
    id: 670,
    team: "Zenit Saint Petersburg",
    country: "Russia",
    code: "RUS_ZEN",
  },
  { id: 671, team: "CSKA Moscow", country: "Russia", code: "RUS_CSK" },
  { id: 672, team: "Dynamo Moscow", country: "Russia", code: "RUS_DYM" },
  { id: 673, team: "Krasnodar", country: "Russia", code: "RUS_KRA" },
  { id: 674, team: "Lokomotiv Moscow", country: "Russia", code: "RUS_LOK" },
  { id: 675, team: "Spartak Moscow", country: "Russia", code: "RUS_SPA" },
  { id: 676, team: "Rostov", country: "Russia", code: "RUS_ROS" },
  { id: 677, team: "Sochi", country: "Russia", code: "RUS_SOC" },
  { id: 678, team: "Orenburg", country: "Russia", code: "RUS_ORE" },
  { id: 679, team: "Akhmat Grozny", country: "Russia", code: "RUS_AKH" },
  {
    id: 680,
    team: "Krylia Sovetov Samara",
    country: "Russia",
    code: "RUS_KRY",
  },
  { id: 681, team: "Ural Yekaterinburg", country: "Russia", code: "RUS_URA" },
  { id: 682, team: "Rubin Kazan", country: "Russia", code: "RUS_RUB" },
  { id: 683, team: "Baltika Kaliningrad", country: "Russia", code: "RUS_BAL" },
  { id: 684, team: "Fakel Voronezh", country: "Russia", code: "RUS_FAK" },
  { id: 685, team: "Pari Nizhny Novgorod", country: "Russia", code: "RUS_PAR" },

  // Ukrainian Premier League Season 2023-2024 (Subject to change)
  { id: 686, team: "Shakhtar Donetsk", country: "Ukraine", code: "UKR_SHA" },
  { id: 687, team: "Dynamo Kyiv", country: "Ukraine", code: "UKR_DYN" },
  { id: 688, team: "Dnipro-1", country: "Ukraine", code: "UKR_DNI" },
  { id: 689, team: "Zorya Luhansk", country: "Ukraine", code: "UKR_ZOR" },
  { id: 690, team: "Vorskla Poltava", country: "Ukraine", code: "UKR_VOR" },
  { id: 691, team: "Kolos Kovalivka", country: "Ukraine", code: "UKR_KOL" },
  { id: 692, team: "Kryvbas Kryvyi Rih", country: "Ukraine", code: "UKR_KRV" },
  { id: 693, team: "FC Oleksandriya", country: "Ukraine", code: "UKR_OLE" },
  { id: 694, team: "Rukh Lviv", country: "Ukraine", code: "UKR_RUK" },
  { id: 695, team: "Obolon Kyiv", country: "Ukraine", code: "UKR_OBO" },
  { id: 696, team: "LNZ Cherkasy", country: "Ukraine", code: "UKR_LNZ" },
  {
    id: 697,
    team: "Metalist 1925 Kharkiv",
    country: "Ukraine",
    code: "UKR_MET",
  },
  { id: 698, team: "Veres Rivne", country: "Ukraine", code: "UKR_VER" },
  { id: 699, team: "Chornomorets Odesa", country: "Ukraine", code: "UKR_CHO" },
  { id: 700, team: "Polissya Zhytomyr", country: "Ukraine", code: "UKR_POL" },
  { id: 701, team: "Minaj", country: "Ukraine", code: "UKR_MIN" },

  // Czech First League Season 2023-2024
  {
    id: 702,
    team: "Sparta Prague",
    country: "Czech Republic",
    code: "CZE_SPA",
  },
  {
    id: 703,
    team: "Slavia Prague",
    country: "Czech Republic",
    code: "CZE_SLA",
  },
  {
    id: 704,
    team: "Viktoria Plzeň",
    country: "Czech Republic",
    code: "CZE_PLZ",
  },
  {
    id: 705,
    team: "Baník Ostrava",
    country: "Czech Republic",
    code: "CZE_OST",
  },
  {
    id: 706,
    team: "Mladá Boleslav",
    country: "Czech Republic",
    code: "CZE_MBO",
  },
  { id: 707, team: "Slovácko", country: "Czech Republic", code: "CZE_SLO" },
  {
    id: 708,
    team: "Sigma Olomouc",
    country: "Czech Republic",
    code: "CZE_OLO",
  },
  {
    id: 709,
    team: "Hradec Králové",
    country: "Czech Republic",
    code: "CZE_HKR",
  },
  { id: 710, team: "Teplice", country: "Czech Republic", code: "CZE_TEP" },
  {
    id: 711,
    team: "Bohemians 1905",
    country: "Czech Republic",
    code: "CZE_BOH",
  },
  { id: 712, team: "FK Pardubice", country: "Czech Republic", code: "CZE_PAR" },
  { id: 713, team: "FK Jablonec", country: "Czech Republic", code: "CZE_JAB" },
  { id: 714, team: "Fastav Zlín", country: "Czech Republic", code: "CZE_ZLI" },
  {
    id: 715,
    team: "Dynamo České Budějovice",
    country: "Czech Republic",
    code: "CZE_CBJ",
  },
  { id: 716, team: "MFK Karviná", country: "Czech Republic", code: "CZE_KAR" },
  {
    id: 717,
    team: "FK Trinity Zlín",
    country: "Czech Republic",
    code: "CZE_TRI",
  }, // Corrected team name

  // Latvian Virslīga Season 2023
  { id: 718, team: "Valmiera", country: "Latvia", code: "LVA_VAL" },
  { id: 719, team: "Riga FC", country: "Latvia", code: "LVA_RFC" },
  { id: 720, team: "FK Auda", country: "Latvia", code: "LVA_AUD" },
  { id: 721, team: "FK RFS", country: "Latvia", code: "LVA_RFS" },
  { id: 722, team: "FK Liepāja", country: "Latvia", code: "LVA_LIE" },
  { id: 723, team: "FS Jelgava", country: "Latvia", code: "LVA_JEL" },
  { id: 724, team: "FK Metta", country: "Latvia", code: "LVA_MET" },
  { id: 725, team: "FK Tukums 2000", country: "Latvia", code: "LVA_TUK" },
  { id: 726, team: "FK Spartaks Jūrmala", country: "Latvia", code: "LVA_SPA" },
  { id: 727, team: "BFC Daugavpils", country: "Latvia", code: "LVA_DAU" },

  // Croatian First Football League Season 2023-2024
  { id: 728, team: "Dinamo Zagreb", country: "Croatia", code: "CRO_DIN" },
  { id: 729, team: "Hajduk Split", country: "Croatia", code: "CRO_HAJ" },
  { id: 730, team: "Rijeka", country: "Croatia", code: "CRO_RIJ" },
  { id: 731, team: "Osijek", country: "Croatia", code: "CRO_OSI" },
  { id: 732, team: "Lokomotiva Zagreb", country: "Croatia", code: "CRO_LOK" },
  { id: 733, team: "Slaven Belupo", country: "Croatia", code: "CRO_SLA" },
  { id: 734, team: "Varaždin", country: "Croatia", code: "CRO_VAR" },
  { id: 735, team: "Istra 1961", country: "Croatia", code: "CRO_IST" },
  { id: 736, team: "Rudeš", country: "Croatia", code: "CRO_RUD" },
  { id: 737, team: "Gorica", country: "Croatia", code: "CRO_GOR" },
];

export default teams;
